* Code Features
** TODO Allow outcome distributions to be both positive and negative

It may be better to use as a two-sided log-normal distribution (i.e. a regular log-normal distribution combined with the same distribution flipped over the Y axis). Unclear about the details.
** TODO Write function to sum multiple distributions where you specify at runtime which are positive or negative
* Model Improvements
** TODO Break down effects on factory-farmed animals into multiple categories for different types of animals
Might be overcomplicated and not worth it
** More comprehensively list plausible far-future outcomes
*** TODO Competitive ems that outcompete humans
see http://www.nickbostrom.com/fut/evolution.html
*** TODO Somehow account for unpredictable outcomes
** TODO Improved prior
Conceptualize estimates as being the top estimates drawn from a larger pool. That means you're more likely to get a good result by chance.

Or figure out a better way to account for the fact that estimates tend to be too high.

*** TODO Look at GiveWell's CEE's from 2007 and see why they're wrong
* Refactor
** TODO For posterior, represent estimate as buckets instead of converting to lognormal distribution, which loses accuracy
* Bugs
** TODO Well-being signs are determined by the way calculations are done and don't change when you change the sign of the input
